import os
import time
from playwright.sync_api import sync_playwright
from pptx import Presentation
from pptx.util import Inches, Pt

def capture_screenshots():
    screenshots = {}
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        
        # 1. Login Page
        page.goto('http://127.0.0.1:5000/auth/login')
        time.sleep(1)
        page.screenshot(path='login.png')
        screenshots['Login'] = 'login.png'
        
        # Log in as admin
        page.fill('input[name="username"]', 'admin')
        page.fill('input[name="password"]', 'admin123')
        page.click('button[type="submit"]')
        time.sleep(2)
        
        # 2. Main Dashboard
        page.screenshot(path='dashboard.png')
        screenshots['Dashboard'] = 'dashboard.png'
        
        # 3. HR Module
        page.goto('http://127.0.0.1:5000/hr/')
        time.sleep(1)
        page.screenshot(path='hr_module.png')
        screenshots['HR Module'] = 'hr_module.png'
        
        # 4. PM Module
        page.goto('http://127.0.0.1:5000/pm/')
        time.sleep(1)
        page.screenshot(path='pm_module.png')
        screenshots['PM Module'] = 'pm_module.png'

        # 5. Finance Module
        page.goto('http://127.0.0.1:5000/finance/')
        time.sleep(1)
        page.screenshot(path='finance_module.png')
        screenshots['Finance Module'] = 'finance_module.png'

        # 6. Employee Space
        page.goto('http://127.0.0.1:5000/employee/')
        time.sleep(1)
        page.screenshot(path='employee_module.png')
        screenshots['Employee Space'] = 'employee_module.png'

        browser.close()
    return screenshots

def create_ppt(screenshots):
    prs = Presentation()

    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Enterprise Portal Application Workflow"
    subtitle.text = "A walkthrough of different stages and modules\nGenerated by Antigravity"

    # Slide for each screenshot
    bullet_slide_layout = prs.slide_layouts[5] # Title only layout

    descriptions = {
        'Login': 'Secure login for all users (Admin, HR, PM, Finance, Employee).',
        'Dashboard': 'Main landing page. Displays accessible modules based on user roles and permissions.',
        'HR Module': 'Manage employees, attendance, leaves, shifts, and HR policies.',
        'PM Module': 'Project tracking, task assignments, milestones, and timesheets.',
        'Finance Module': 'Expense claims, invoices, and salary record generation.',
        'Employee Space': 'Self-service portal for attendance check-in, leave requests, and profile updates.'
    }

    for name, img_path in screenshots.items():
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        title_shape.text = name

        # Add image
        left = Inches(1)
        top = Inches(1.5)
        height = Inches(4.5)
        shapes.add_picture(img_path, left, top, height=height)

        # Add description text box
        txBox = slide.shapes.add_textbox(Inches(1), Inches(6.2), Inches(8), Inches(1))
        tf = txBox.text_frame
        tf.text = descriptions.get(name, "")
        for p in tf.paragraphs:
            p.font.size = Pt(18)

    ppt_path = "Application_Workflow.pptx"
    prs.save(ppt_path)
    print(f"Presentation saved to {ppt_path}")

if __name__ == "__main__":
    print("Capturing screenshots...")
    screenshots = capture_screenshots()
    print("Generating PPT...")
    create_ppt(screenshots)
