"""Add demographics to Employee

Revision ID: 3caff801ded8
Revises: b6c934fdf445
Create Date: 2026-05-11 14:39:55.977496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caff801ded8'
down_revision = 'b6c934fdf445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('aadhar_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('aadhar_number')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
