"""Add reporting_manager_id to Employee and is_urgent to Leave

Revision ID: b6c934fdf445
Revises: 5c36daef18ab
Create Date: 2026-05-08 11:11:13.155278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c934fdf445'
down_revision = '5c36daef18ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporting_manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_employee_reporting_manager', 'employees', ['reporting_manager_id'], ['id'])

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_urgent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_column('is_urgent')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_reporting_manager', type_='foreignkey')
        batch_op.drop_column('reporting_manager_id')

    # ### end Alembic commands ###
